# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Wed Sep 29 12:04:37 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1163, 656)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mpl_layout_space = QtWidgets.QGridLayout()
        self.mpl_layout_space.setObjectName("mpl_layout_space")
        self.gridLayout.addLayout(self.mpl_layout_space, 0, 1, 2, 1)
        self.refresh_button = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_button.setObjectName("refresh_button")
        self.gridLayout.addWidget(self.refresh_button, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(260, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(260, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 240, 241, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.init_light_azimuth_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.init_light_azimuth_spinbox.setGeometry(QtCore.QRect(160, 30, 71, 26))
        self.init_light_azimuth_spinbox.setMaximum(359)
        self.init_light_azimuth_spinbox.setObjectName("init_light_azimuth_spinbox")
        self.init_light_elevation_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.init_light_elevation_spinbox.setGeometry(QtCore.QRect(160, 60, 71, 26))
        self.init_light_elevation_spinbox.setMaximum(359)
        self.init_light_elevation_spinbox.setObjectName("init_light_elevation_spinbox")
        self.init_wind_azimuth_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.init_wind_azimuth_spinbox.setGeometry(QtCore.QRect(160, 90, 70, 26))
        self.init_wind_azimuth_spinbox.setMaximum(359)
        self.init_wind_azimuth_spinbox.setObjectName("init_wind_azimuth_spinbox")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 140, 26))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(13, 60, 140, 26))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(19, 90, 141, 26))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(34, 120, 120, 26))
        self.label_6.setObjectName("label_6")
        self.init_wind_speed_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.init_wind_speed_spinbox.setGeometry(QtCore.QRect(160, 120, 69, 26))
        self.init_wind_speed_spinbox.setObjectName("init_wind_speed_spinbox")
        self.sim_combobox = QtWidgets.QComboBox(self.groupBox)
        self.sim_combobox.setGeometry(QtCore.QRect(70, 30, 171, 25))
        self.sim_combobox.setToolTip("")
        self.sim_combobox.setObjectName("sim_combobox")
        self.sim_combobox.addItem("")
        self.sim_combobox.addItem("")
        self.sim_combobox.addItem("")
        self.sim_combobox.addItem("")
        self.sim_combobox.addItem("")
        self.sim_combobox.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 25))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(42, 60, 21, 25))
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 390, 241, 150))
        self.groupBox_3.setObjectName("groupBox_3")
        self.conf_light_azimuth_spinbox = QtWidgets.QSpinBox(self.groupBox_3)
        self.conf_light_azimuth_spinbox.setGeometry(QtCore.QRect(160, 30, 71, 26))
        self.conf_light_azimuth_spinbox.setMaximum(359)
        self.conf_light_azimuth_spinbox.setObjectName("conf_light_azimuth_spinbox")
        self.conf_light_elevation_spinbox = QtWidgets.QSpinBox(self.groupBox_3)
        self.conf_light_elevation_spinbox.setGeometry(QtCore.QRect(160, 60, 71, 26))
        self.conf_light_elevation_spinbox.setMaximum(359)
        self.conf_light_elevation_spinbox.setObjectName("conf_light_elevation_spinbox")
        self.conf_wind_azimuth_spinbox = QtWidgets.QSpinBox(self.groupBox_3)
        self.conf_wind_azimuth_spinbox.setGeometry(QtCore.QRect(160, 90, 70, 26))
        self.conf_wind_azimuth_spinbox.setMaximum(359)
        self.conf_wind_azimuth_spinbox.setObjectName("conf_wind_azimuth_spinbox")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 140, 26))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(13, 60, 140, 26))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(19, 90, 141, 26))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(34, 120, 120, 26))
        self.label_10.setObjectName("label_10")
        self.conf_wind_speed_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.conf_wind_speed_spinbox.setGeometry(QtCore.QRect(160, 120, 69, 26))
        self.conf_wind_speed_spinbox.setObjectName("conf_wind_speed_spinbox")
        self.title_lineedit = QtWidgets.QLineEdit(self.groupBox)
        self.title_lineedit.setGeometry(QtCore.QRect(70, 90, 113, 25))
        self.title_lineedit.setObjectName("title_lineedit")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(30, 90, 30, 25))
        self.label_11.setObjectName("label_11")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 220, 240, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.options_stack = QtWidgets.QStackedWidget(self.groupBox)
        self.options_stack.setEnabled(False)
        self.options_stack.setGeometry(QtCore.QRect(10, 120, 241, 101))
        self.options_stack.setObjectName("options_stack")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 0, 240, 100))
        self.groupBox_6.setObjectName("groupBox_6")
        self.options_stack.addWidget(self.page_3)
        self.bws_page = QtWidgets.QWidget()
        self.bws_page.setObjectName("bws_page")
        self.bws_groupBox = QtWidgets.QGroupBox(self.bws_page)
        self.bws_groupBox.setGeometry(QtCore.QRect(0, 0, 240, 100))
        self.bws_groupBox.setObjectName("bws_groupBox")
        self.bws_slope_spinbox = QtWidgets.QDoubleSpinBox(self.bws_groupBox)
        self.bws_slope_spinbox.setGeometry(QtCore.QRect(120, 30, 91, 26))
        self.bws_slope_spinbox.setDecimals(3)
        self.bws_slope_spinbox.setMinimum(-1.0)
        self.bws_slope_spinbox.setMaximum(1000.0)
        self.bws_slope_spinbox.setSingleStep(1.0)
        self.bws_slope_spinbox.setProperty("value", 53.0)
        self.bws_slope_spinbox.setObjectName("bws_slope_spinbox")
        self.bws_variance_spinbox = QtWidgets.QDoubleSpinBox(self.bws_groupBox)
        self.bws_variance_spinbox.setGeometry(QtCore.QRect(120, 60, 91, 26))
        self.bws_variance_spinbox.setDecimals(6)
        self.bws_variance_spinbox.setSingleStep(0.0001)
        self.bws_variance_spinbox.setProperty("value", 0.000303)
        self.bws_variance_spinbox.setObjectName("bws_variance_spinbox")
        self.label_13 = QtWidgets.QLabel(self.bws_groupBox)
        self.label_13.setGeometry(QtCore.QRect(39, 30, 81, 26))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.bws_groupBox)
        self.label_14.setGeometry(QtCore.QRect(20, 60, 91, 26))
        self.label_14.setObjectName("label_14")
        self.options_stack.addWidget(self.bws_page)
        self.nws_page = QtWidgets.QWidget()
        self.nws_page.setObjectName("nws_page")
        self.nws_groupBox = QtWidgets.QGroupBox(self.nws_page)
        self.nws_groupBox.setGeometry(QtCore.QRect(0, 0, 240, 100))
        self.nws_groupBox.setObjectName("nws_groupBox")
        self.nws_slope_spinbox = QtWidgets.QDoubleSpinBox(self.nws_groupBox)
        self.nws_slope_spinbox.setGeometry(QtCore.QRect(120, 30, 91, 26))
        self.nws_slope_spinbox.setDecimals(3)
        self.nws_slope_spinbox.setMinimum(-1.0)
        self.nws_slope_spinbox.setMaximum(1000.0)
        self.nws_slope_spinbox.setSingleStep(1.0)
        self.nws_slope_spinbox.setProperty("value", 53.0)
        self.nws_slope_spinbox.setObjectName("nws_slope_spinbox")
        self.label_15 = QtWidgets.QLabel(self.nws_groupBox)
        self.label_15.setGeometry(QtCore.QRect(39, 30, 81, 26))
        self.label_15.setObjectName("label_15")
        self.options_stack.addWidget(self.nws_page)
        self.sc_page = QtWidgets.QWidget()
        self.sc_page.setObjectName("sc_page")
        self.groupBox_4 = QtWidgets.QGroupBox(self.sc_page)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 240, 100))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(20, 30, 31, 25))
        self.label_12.setObjectName("label_12")
        self.sc_cue_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.sc_cue_combobox.setGeometry(QtCore.QRect(60, 30, 61, 25))
        self.sc_cue_combobox.setToolTip("")
        self.sc_cue_combobox.setObjectName("sc_cue_combobox")
        self.sc_cue_combobox.addItem("")
        self.sc_cue_combobox.addItem("")
        self.options_stack.addWidget(self.sc_page)
        self.n_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.n_spinbox.setGeometry(QtCore.QRect(70, 60, 48, 26))
        self.n_spinbox.setMaximum(1000000)
        self.n_spinbox.setProperty("value", 30)
        self.n_spinbox.setObjectName("n_spinbox")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1163, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.options_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.refresh_button.setText(QtWidgets.QApplication.translate("MainWindow", "Refresh", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Initial", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Light Azimuth (deg)", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Light Elevation (deg)", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Wind Azimuth (deg)", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Wind Speed (m/s)", None, -1))
        self.sim_combobox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Weighted Vector Sum", None, -1))
        self.sim_combobox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Non-optimal Weighted Sum", None, -1))
        self.sim_combobox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Biased non-optimal Weighted Sum", None, -1))
        self.sim_combobox.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Weighted Arithmetic Mean", None, -1))
        self.sim_combobox.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "Winner Take All", None, -1))
        self.sim_combobox.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "Single Cue", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Method", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "n = ", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Conflict", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Light Azimuth (deg)", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Light Elevation (deg)", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Wind Azimuth (deg)", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Wind Speed (m/s)", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Title", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.bws_groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Adj. slope", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Bias variance", None, -1))
        self.nws_groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Adj. slope", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Cue", None, -1))
        self.sc_cue_combobox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Light", None, -1))
        self.sc_cue_combobox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Wind", None, -1))

