# Cue combination simulator configuration example;

# Treatment 1: Wind speed 2.5m/s, Light elevation: 45deg, Conflict: 120deg
treatment-parameters:
  # String - A unique name for this condition - used to organise output
  treatment-id: "w:2.5,l:5,c:120"

# Integer - The number of trials you want the software to simulate
  number-of-trials: 1000

# The initial conditions (cues aligned)
initial-condition:
  light:
    elevation: 5 # Integer - Light elevation (in degrees)
    azimuth: 0    # Integer - Light azimuthal position (in degrees)

  wind:
    azimuth: 0  # Integer - The prevailing azimuth of the wind (in degrees)
    speed: 2.5  # Float - The wind speed expressed in m/s

# The conflict conditions
conflict-condition:
  light:
    elevation: 5
    azimuth: 0

  wind:
    azimuth: 120
    speed: 2.5
